# Generated by Django 3.1.5 on 2022-01-29 22:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='titleHome',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HomePageAboutUsPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('aboutUs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.aboutus')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutUs_placements', to='home.homepage')),
            ],
            options={
                'verbose_name': 'aboutUs placement',
                'verbose_name_plural': 'aboutUs placements',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
