# Generated by Django 3.1.5 on 2022-02-01 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220129_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='About date'),
            preserve_default=False,
        ),
    ]
